services:
    Octopouce\ShopBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources}'
        autowire: true
        autoconfigure: true
        public: false
